# Numpy Basics <hr style="border:2.5px solid rgb(46, 40, 221)"></hr>

Data Analsyt: Arlee D. Tanaman <br>
Department: Electrical Engineering

In [24]:
# import and packages
import numpy as np
from scipy import stats

# 1D Array

In [42]:
array_a = np.array([1, 2, 3])
array_a

array([1, 2, 3])

# 2D Array

In [44]:
my_array = np.array([
    [1, 2, 3],[4, 5, 6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
my_array.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
my_array = my_array.T

In [47]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [49]:
# add by row
np.sum(my_array, axis=0)

array([ 6, 15])

In [51]:
# add by column
np.sum(my_array, axis=1)

array([5, 7, 9])

# The Measures of Central Tendency

In [25]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [26]:
# mean
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [27]:
# meadian
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [28]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguar vs. Panther

## Jaguar

In [29]:
jaguar = np.array([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])

In [30]:
# jaguar mean
jaguar_mean = np.mean(jaguar)
jaguar_mean

np.float64(9.399999999999999)

In [31]:
# jaguar median
jaguar_median = np.median(jaguar)
jaguar_median

np.float64(9.8)

In [32]:
# jaguar mode
jaguar_mode = stats.mode(jaguar)
jaguar_mode

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [70]:
# jaguar sample standard deviation
jaguar_std = np.std(jaguar, ddof=1)
jaguar_std

np.float64(2.2045407685048604)

In [67]:
# jaguar variance
jaguar_var = np.var(jaguar, ddof=1)
jaguar_var

np.float64(4.86)

In [66]:
# jaguar range
max_jaguar = np.max(jaguar)
min_jaguar = np.min(jaguar)

range_jaguar = max_jaguar - min_jaguar
range_jaguar

np.float64(8.0)

In [60]:
# q1 jaguar percentile 1
q1_jaguar = np.percentile(jaguar, 25)
q1_jaguar

np.float64(9.4)

In [65]:
# q2 jaguar median percentile 2
q2_jaguar = np.percentile(jaguar, 50)
q2_jaguar

np.float64(9.8)

In [63]:
# q3 jaguar percentile 3
q3_jaguar = np.percentile(jaguar, 75)
q3_jaguar

np.float64(10.45)

In [62]:
# Jaguar IQR
iqr_jaguar = q3_jaguar - q1_jaguar
iqr_jaguar

np.float64(1.049999999999999)

## Panther

In [33]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])

In [34]:
# panther mean
panther_mean = np.mean(panther)
panther_mean

np.float64(10.75)

In [35]:
# panther median
panther_median = np.median(panther)
panther_median

np.float64(9.55)

In [36]:
# panther mode
panther_mode = stats.mode(panther)
panther_mode

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [71]:
# panther sample standard deviation
panther_std = np.std(panther, ddof=1)
panther_std

np.float64(3.3290806204983645)

In [69]:
# panther variance
panther_var = np.var(panther, ddof=1)
panther_var

np.float64(11.082777777777777)

In [68]:
# panther range
max_panther = np.max(panther)
min_panther = np.min(panther)

range_panther = max_panther - min_panther
range_panther

np.float64(10.9)

In [75]:
# q1 panther percentile 1
q1_panther = np.percentile(panther, 25)
q1_panther


np.float64(9.125)

In [ ]:
# q2 panther median percentile 2
q2_panther = np.percentile(panther, 50)
q2_panther

np.float64(9.55)

In [73]:
# q3 panther percentile 3
q3_panther = np.percentile(panther, 75)
q3_panther

np.float64(10.625)

In [72]:
# IQR panther
iqr_panther = q3_panther - q1_panther
iqr_panther

np.float64(1.5)